# Generated by Django 6.0.2 on 2026-02-18 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Stock actual')),
                ('stock_minimo', models.IntegerField(default=0, help_text='Umbral para alerta de stock bajo', verbose_name='Stock mínimo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('variante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='products.varianteproducto', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada_compra', 'Entrada por compra'), ('entrada_ajuste', 'Entrada por ajuste'), ('entrada_devolucion', 'Entrada por devolución'), ('salida_venta', 'Salida por venta'), ('salida_merma', 'Salida por merma'), ('salida_sin_stock', 'Salida sin stock'), ('ajuste_manual', 'Ajuste manual')], db_index=True, max_length=30, verbose_name='Tipo de movimiento')),
                ('cantidad', models.IntegerField(help_text='Positivo = entrada, Negativo = salida', verbose_name='Cantidad')),
                ('stock_anterior', models.IntegerField(verbose_name='Stock antes del movimiento')),
                ('stock_nuevo', models.IntegerField(verbose_name='Stock después del movimiento')),
                ('referencia_id', models.IntegerField(blank=True, help_text='ID de venta/ajuste/devolución que originó', null=True, verbose_name='ID de referencia')),
                ('referencia_tipo', models.CharField(blank=True, choices=[('venta', 'Venta'), ('ajuste', 'Ajuste'), ('merma', 'Merma'), ('devolucion', 'Devolución')], max_length=30, null=True, verbose_name='Tipo de referencia')),
                ('motivo', models.CharField(blank=True, default='', help_text='Obligatorio en ajustes y mermas', max_length=200, verbose_name='Motivo')),
                ('autorizacion_id', models.IntegerField(blank=True, help_text='Si requirió autorización', null=True, verbose_name='ID de autorización')),
                ('fecha', models.DateTimeField(db_index=True, verbose_name='Fecha del movimiento')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventory.inventario', verbose_name='Inventario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
                ('variante', models.ForeignKey(help_text='Redundancia para consultas rápidas', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='products.varianteproducto', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'db_table': 'movimiento_inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['stock_actual'], name='idx_inventario_stock'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['variante'], name='idx_inventario_variante'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['variante'], name='idx_mov_inv_variante'),
        ),
    ]
