# Generated by Django 6.0.2 on 2026-04-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='LMSolutions', help_text='Aparece en el encabezado de los tickets impresos.', max_length=100, verbose_name='Nombre del negocio')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración del Negocio',
                'verbose_name_plural': 'Configuración del Negocio',
            },
        ),
    ]
