# Generated by Django 6.0.2 on 2026-02-18 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Teléfono')),
                ('email', models.CharField(blank=True, default='', max_length=100, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(blank=True, default='', verbose_name='Dirección')),
                ('tipo_cliente', models.CharField(default='general', max_length=50, verbose_name='Tipo de cliente')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, help_text='0 = sin crédito', max_digits=12, verbose_name='Límite de crédito')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, help_text='Campo desnormalizado, recalculable desde movimiento_credito', max_digits=12, verbose_name='Saldo pendiente actual')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='idx_cliente_nombre'), models.Index(fields=['telefono'], name='idx_cliente_telefono')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devolucion_id', models.IntegerField(blank=True, help_text='FK lógica a devolución (módulo aún no implementado)', null=True, verbose_name='ID de devolución')),
                ('tipo', models.CharField(choices=[('cargo', 'Cargo por venta'), ('abono', 'Abono por pago'), ('ajuste', 'Ajuste manual')], max_length=30, verbose_name='Tipo de movimiento')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Siempre positivo', max_digits=12, verbose_name='Monto')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo antes del movimiento')),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo después del movimiento')),
                ('descripcion', models.CharField(blank=True, default='', max_length=200, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del movimiento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_credito', to='customers.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Movimiento de crédito',
                'verbose_name_plural': 'Movimientos de crédito',
                'db_table': 'movimiento_credito',
                'ordering': ['-fecha'],
            },
        ),
    ]
