# Generated by Django 6.0.2 on 2026-02-18 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('payments', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocredito',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_credito', to='payments.pago', verbose_name='Pago asociado'),
        ),
        migrations.AddField(
            model_name='movimientocredito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_credito', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='movimientocredito',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_credito', to='sales.venta', verbose_name='Venta asociada'),
        ),
        migrations.AddIndex(
            model_name='movimientocredito',
            index=models.Index(fields=['cliente'], name='idx_mov_credito_cliente'),
        ),
    ]
