# Generated by Django 6.0.2 on 2026-02-18 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cliente', models.DecimalField(decimal_places=2, help_text='Monto que reduce la deuda del cliente', max_digits=12, verbose_name='Monto al cliente')),
                ('cargo_tarjeta', models.DecimalField(decimal_places=2, default=0, help_text='Suma de cargos por interés de tarjeta', max_digits=12, verbose_name='Cargo por tarjeta')),
                ('total_cobrado', models.DecimalField(decimal_places=2, help_text='monto_cliente + cargo_tarjeta', max_digits=12, verbose_name='Total cobrado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='customers.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='sales.venta', verbose_name='Venta asociada')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PagoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=20, verbose_name='Método de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('con_intereses', models.BooleanField(default=False, verbose_name='Con intereses')),
                ('porcentaje_interes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de interés')),
                ('cargo_generado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cargo generado')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='payments.pago', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Detalle de pago',
                'verbose_name_plural': 'Detalles de pago',
                'db_table': 'pago_detalle',
            },
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['venta'], name='idx_pago_venta'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['cliente'], name='idx_pago_cliente'),
        ),
    ]
