# Generated by Django 6.0.2 on 2026-02-18 01:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto inicial')),
                ('total_efectivo_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_tarjeta_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_transferencia_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_efectivo_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_tarjeta_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_transferencia_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diferencia_efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diferencia_tarjeta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diferencia_transferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observaciones_cierre', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_abiertas', to=settings.AUTH_USER_MODEL, verbose_name='usuario apertura')),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_cerradas', to=settings.AUTH_USER_MODEL, verbose_name='usuario cierre')),
            ],
            options={
                'db_table': 'caja',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=20)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.CharField(max_length=200)),
                ('origen', models.CharField(blank=True, choices=[('venta', 'Venta'), ('abono', 'Abono'), ('manual', 'Manual'), ('devolucion', 'Devolución')], max_length=30, null=True)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='cash.caja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movimiento_caja',
            },
        ),
        migrations.AddIndex(
            model_name='caja',
            index=models.Index(fields=['usuario_apertura'], name='idx_caja_usuario'),
        ),
        migrations.AddIndex(
            model_name='caja',
            index=models.Index(fields=['estado'], name='idx_caja_estado'),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('usuario_apertura',), name='unique_caja_abierta_por_usuario'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['caja'], name='idx_movimiento_caja_caja'),
        ),
    ]
