# Generated by Django 6.0.2 on 2026-02-18 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la marca')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marca',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de producto',
                'verbose_name_plural': 'Tipos de producto',
                'db_table': 'tipo_producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('codigo_interno', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código interno')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.categoria', verbose_name='Categoría')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.marca', verbose_name='Marca')),
                ('tipo_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.tipoproducto', verbose_name='Tipo de producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la variante')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='SKU')),
                ('atributos', models.JSONField(blank=True, default=dict, help_text='Ej: {"talla": "S", "color": "Negro"}', verbose_name='Atributos flexibles')),
                ('es_default', models.BooleanField(default=False, verbose_name='Variante por defecto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='products.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variantes de producto',
                'db_table': 'variante_producto',
                'ordering': ['producto', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, help_text='Solo visible para administrador', max_digits=12, null=True, verbose_name='Precio de compra')),
                ('precio_contado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de contado')),
                ('precio_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio a crédito')),
                ('porcentaje_ganancia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de ganancia')),
                ('vigente', models.BooleanField(default=True, help_text='Solo un precio vigente por variante', verbose_name='Vigente')),
                ('motivo_cambio', models.CharField(blank=True, default='', max_length=200, verbose_name='Motivo del cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precios_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='products.varianteproducto', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Precio de producto',
                'verbose_name_plural': 'Precios de producto',
                'db_table': 'precio_producto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodigoBarras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Código de barras')),
                ('principal', models.BooleanField(default=False, verbose_name='Código principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_barras', to='products.varianteproducto', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Código de barras',
                'verbose_name_plural': 'Códigos de barras',
                'db_table': 'codigo_barras',
            },
        ),
        migrations.AddIndex(
            model_name='varianteproducto',
            index=models.Index(fields=['producto'], name='idx_variante_producto'),
        ),
        migrations.AddConstraint(
            model_name='varianteproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'nombre'), name='uq_variante_producto_nombre'),
        ),
        migrations.AddIndex(
            model_name='precioproducto',
            index=models.Index(fields=['variante', 'vigente'], name='idx_precio_vigente'),
        ),
    ]
